project:
  type: website
  output-dir: docs

website:
  title: "CICLISMO REALE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - squadre.qmd
      - cq_ranking.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    grid: 
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 200px


